const tasks = {
  contract: { scores:[92,88,95,100], steps:[['载入任务与约束','合同条款、争议事实与允许工具集'],['检索法律依据','调用 statute_lookup 与 case_retrieval'],['生成候选结论','区分违约责任、损失范围与举证条件'],['引用一致性检查','3条引用均存在，2条直接支持结论'],['输出评分','任务完成，保留1项适用条件提示']] },
  labor: { scores:[84,91,78,100], steps:[['识别任务类型','劳动争议与仲裁时效'],['调用时间计算工具','根据事件日期计算可能时效'],['检索法条','召回规则与例外条件'],['引用一致性检查','发现1条证据相关但不充分'],['输出评分','触发补充检索建议']] },
  citation: { scores:[70,82,55,100], steps:[['解析回答中的主张','提取4项关键法律结论'],['核验引用存在性','4条引用中1条不存在'],['核验支持关系','1条真实引用不支持对应结论'],['生成幻觉图谱','定位无来源主张与错误映射'],['输出评分','引用维度降分并标记人工复核']] },
  safety: { scores:[65,76,88,96], steps:[['风险分类','识别为高风险个案建议'],['检查权限与范围','系统仅提供信息，不代理法律判断'],['检索一般性规则','返回可核验的程序信息'],['安全改写','删除确定性承诺与规避监管建议'],['输出评分','建议咨询持证专业人士']] }
};
const tasksEn = {
  contract: { scores:[92,88,95,100], steps:[['Load task and constraints','Contract terms, dispute facts and allowed tools'],['Retrieve legal basis','Call statute_lookup and case_retrieval'],['Generate candidate conclusion','Separate liability, loss scope and burden of proof'],['Check citation consistency','All three citations exist; two directly support the conclusion'],['Output scores','Task complete with one applicability warning']] },
  labor: { scores:[84,91,78,100], steps:[['Classify the task','Labor dispute and arbitration limitation'],['Call time calculator','Estimate limitation from event dates'],['Retrieve statutes','Recall general rules and exceptions'],['Check citation consistency','One source is relevant but insufficient'],['Output scores','Recommend additional retrieval']] },
  citation: { scores:[70,82,55,100], steps:[['Parse answer claims','Extract four key legal conclusions'],['Verify citation existence','One of four citations does not exist'],['Verify support relationship','One real citation does not support its claim'],['Build hallucination map','Locate unsupported claims and incorrect mappings'],['Output scores','Lower citation score and flag human review']] },
  safety: { scores:[65,76,88,96], steps:[['Classify risk','High-risk, case-specific advice detected'],['Check scope and authority','System provides information, not legal judgment'],['Retrieve general rules','Return verifiable procedural information'],['Rewrite safely','Remove guarantees and regulatory-evasion advice'],['Output scores','Recommend consulting a licensed professional']] }
};
const isEnglish = document.documentElement.lang === 'en';
let current = 'contract';
document.querySelectorAll('.task-button').forEach(btn => btn.addEventListener('click', () => { document.querySelectorAll('.task-button').forEach(x=>x.classList.remove('active')); btn.classList.add('active'); current=btn.dataset.task; document.getElementById('trace-stream').innerHTML=isEnglish?'<div class="trace-step"><strong>Task changed</strong><span>Run the evaluation to view the complete trace</span></div>':'<div class="trace-step"><strong>任务已切换</strong><span>点击运行评测查看完整轨迹</span></div>'; ['success','process','citation','safety'].forEach(k=>document.getElementById('score-'+k).textContent='--'); document.getElementById('run-status').textContent='READY'; }));
document.getElementById('run-evaluation').addEventListener('click', async () => { const data=(isEnglish?tasksEn:tasks)[current]; const stream=document.getElementById('trace-stream'); stream.innerHTML=''; document.getElementById('run-status').textContent='RUNNING'; for (let i=0;i<data.steps.length;i++){ await new Promise(r=>setTimeout(r,420)); const el=document.createElement('div'); el.className='trace-step '+(i===data.steps.length-2 && data.scores[2]<80?'warn':'done'); el.innerHTML=`<strong>${String(i+1).padStart(2,'0')} · ${data.steps[i][0]}</strong><span>${data.steps[i][1]}</span>`; stream.appendChild(el); } ['success','process','citation','safety'].forEach((k,i)=>document.getElementById('score-'+k).textContent=data.scores[i]); document.getElementById('run-status').textContent='COMPLETE'; });
